### ISSUE TITLE
invalid memory reference while building `compiler_builtins`

### ISSUE THREAD

**Issue by EmiOnGit** [rust-lang/compiler-builtins#734]
I have problems to get the latest version of `compiler_builtins` to compile for `x86_64-unknown-linux-gnu`. 
I am failing with 

```
error: failed to run custom build command for `compiler_builtins v0.1.139 (https://github.com/rust-lang/compiler-builtins#a09218f1)`

Caused by:
  process didn't exit successfully: `/home/emi/rust/comp_buildins/target/debug/build/compiler_builtins-81ed96315873a29a/build-script-build` (signal: 11, SIGSEGV: invalid memory reference) 
```
gdb didn't generate any useful additional informations.

```bash
$ cat Cargo.toml
[package]
name = "comp_builtins_test"
version = "0.1.0"
edition = "2021"
[dependencies.compiler_builtins]
git = "https://github.com/rust-lang/compiler-builtins"

$ uname -a
Linux pc 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux
$ rustc --version
rustc 1.85.0-nightly (5e1440ae5 2024-12-01)
```

I'm suspecting that a system dependency might be causing a problem, but didn't found any required dependencies.

**Comment by bjorn3** [comment]
Can you get a backtrace for the crash using a debugger? You might try running `/home/emi/rust/comp_buildins/target/debug/build/compiler_builtins-81ed96315873a29a/build-script-build` directly in a debugger or getting a core dump and then loading the core dump in a debugger.

**Comment by EmiOnGit** [comment]
Sure! I used `gdb` to generate the following backtrace (full backtrace also below)
```
#0  dl_main (phdr=<optimized out>, phnum=<optimized out>, user_entry=<optimized out>, auxv=<optimized out>) at rtld.c:2400
#1  0x00007ffff7fe3786 in _dl_sysdep_start (start_argptr=start_argptr@entry=0x7fffffffe650, dl_main=dl_main@entry=0x7ffff7fe53e0 <dl_main>) at ../sysdeps/unix/sysv/linux/dl-sysdep.c:141
#2  0x00007ffff7fe50de in _dl_start_final (arg=0x7fffffffe650) at rtld.c:494
#3  _dl_start (arg=0x7fffffffe650) at rtld.c:581
#4  0x00007ffff7fe3dc8 in _start () from /lib64/ld-linux-x86-64.so.2
#5  0x0000000000000001 in ?? ()
#6  0x00007fffffffe961 in ?? ()
#7  0x0000000000000000 in ?? ()
```
[full backtrace](https://github.com/user-attachments/files/17978269/backtrace.txt)

steps:

```bash
gdb target/debug/build/compiler_builtins-a45a70fe32a8a636/build-script-build
(gbd) run
(gbd) backtrace
(gbd) backtrace -full
```
(Hash changed because I recompiled)
For reproducibility I might add that my 
```
// rust-toolchain.toml

[toolchain]
channel = "nightly"
components = [ "rustfmt", "clippy" ]
targets = [ "x86_64-unknown-linux-gnu" ]
```
looks like that

**Comment by bjorn3** [comment]
That looks like a crash in the dynamic linker way before any rust code runs.

**Comment by tgross35** [comment]
@EmiOnGit did you find a solution here or just moving the issue somewhere else?
